### ISSUE TITLE
Set fuel price as multiple of AEO scenario

### ISSUE THREAD

**Issue by gschivley** [PowerGenome/PowerGenome#210]
Current behavior lets users select different AEO scenarios for price forecasts. For example, the AEO scenarios might be

```yaml
eia_series_scenario_names:
  reference: REF2021
  low_price: LOWPRICE
  high_price: HIGHPRICE
  high_resource: HIGHOGS
  low_resource: LOWOGS
```
and all fuels might use the "reference" scenario
```yaml
aeo_fuel_scenarios:
  coal: reference
  naturalgas: reference
  distillate: reference
  uranium: reference
```

This lets users test a few different possible prices for each fuel based on the results published in EIA's AEO. But it constrains prices to those provided by AEO. 

As an additional option, let users add a multiplier for fuel prices from one of the scenarios (e.g. 1.3x the `reference` price). This could be done by changing the "value" part of `aeo_fuel_scenarios` from a string to a list.

```yaml
aeo_fuel_scenarios:
  coal: reference
  naturalgas: [reference, 1.3]
  distillate: reference
  uranium: reference
```

In theory it could also be more complex, using any of the python operators "add", "mul", "truediv", or "sub".

```yaml
aeo_fuel_scenarios:
  coal: reference
  naturalgas: [reference, [add, 3]]
  distillate: reference
  uranium: reference
```

@bradenpecora did you ask about setting different regional cost multipliers for your ERCOT zones? Is there some way to tie this in to that?

**Comment by bradenpecora** [comment]
Yes, it would be great to have. I can think of a couple of ways to do it. It's pretty difficult to come up with a way that yields the most functionality while still being user friendly. It would be great to be able to specify a multiplier for each fuel and region. 

How about something like this?
```yaml
aeo_fuel_region_map:
  west_south_central: [ERC_PHDL, ERC_REST, ERC_WEST, SPP_WEST, ...]

regional_fuel_adjustments:
  ERC_PHDL: 1.5 # multiply all final prices specified by other settings by 1.5
  ERC_REST:
    coal: low_price # override AEO scenario selection from earlier settings
    natural_gas: [high_price, 1.5]
    distillate: 1.5
  ERC_WEST: [reference, 1.5] # apply reference x1.5 to all fuels in ERC_WEST
  SPP_WEST: low_price
```
where each adjustment here would still use the AEO data for `west_south_central` as a basis.

Maybe that is too many options? Happy to help with implementation on that as well.

**Comment by gschivley** [comment]
So this would let users

1. Multiply all fuels within a region by a factor. 
2. Set different cost scenarios for each fuel within a region
3. Set different scenarios for a fuel across regions

It could also take `[op, value]` to add/subtract rather than multiply. Scaling is nice but I can absolutely see someone wanting to add $1 per mmbtu rather than increasing by 20%.

I try to keep things simple but maybe it's best to add all the features now. The only one that I'm on the fence about is different cost scenarios across regions. The prices are exogenous to capacity expansion models but at least they're outputs of single internally-consistent modeling run from NEMS. Setting different scenarios *and* being able to modify the prices might be a bit much.

Without (3), it would look like this

```yaml
aeo_fuel_region_map:
  west_south_central: [ERC_PHDL, ERC_REST, ERC_WEST, SPP_WEST, ...]

aeo_fuel_scenarios:
  coal: reference
  naturalgas: reference
  distillate: reference
  uranium: reference

regional_fuel_adjustments:
  ERC_PHDL: [mul, 1.5] # multiply all reference prices by 1.5
  ERC_REST:
    coal: [sub, 1] # subtract $1 from there reference coal price in this region, keep other fuel prices at "reference"
  ERC_WEST: 
    naturalgas: [add, 1.5] # add $1.50 to the reference price of natural gas
```

Let me loop in @JesseJenkins @xuqingyu and @nspatank to get their perspective.
